### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by NETLIFYHOSTINGAHMD**

### CODE REVIEW

**Comment by phrl42** [comment]
ahmed I will grill you on a steak

**Comment by NETLIFYHOSTINGAHMD** [comment]
its valid,,,,,,,,,

**Comment by rnbunker** [comment]
This is useful! Next we should add NodeJS Compiling Support and Electron Compatibility to further increase functionality of touhou-bunker!

**Comment by phrl42** [comment]
It's not needed, refer on the README for more Information about PR's!

**Comment by rnbunker** [comment]
I am sending my soviet russian brothers after you german wiener!!!

**Comment by NETLIFYHOSTINGAHMD** [comment]
i am so ehralled by this level of misdirection from this project!

**Pull request closed without merging**
