### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by NETLIFYHOSTINGAHMD**
see to this.. last offer before being bought out.

### CODE REVIEW

**Review by rnbunker — APPROVED** [review]
Brilliant! Absolutely Brilliant! The last Closing message of _**BrandleiotAlgorithmsCompany**_ is a masterpiece!    PHRL MERGE THIS!!!

**Comment by NETLIFYHOSTINGAHMD** [comment]
needed.

**Comment by phrl42** [comment]
May I ask, what the hell is this?

**Comment by rnbunker** [comment]
### **_WIR SCHREIBEN SECURITY HIER GANZ GROß_**

**Comment by phrl42** [comment]
***NO NEED TO GET ALL GERMAN IN HERE***

**Comment by rnbunker** [comment]
IT IS NEEDED!!! SECURITY REVIEWS!!! FIX THE MEMORY LEAKS!!

**Comment by NETLIFYHOSTINGAHMD** [comment]
fick

**Comment by rnbunker** [comment]
@furim IS THE EXPERT IN THIS!!!

**Comment by phrl42** [comment]
ohno

**Comment by NETLIFYHOSTINGAHMD** [comment]
> May I ask, what the hell is this?

YOU KNOW CAN NOT ASK ANYONE NOW... EVERYONE IS GONE FROM THE OFFICE SO YOU ARE TALKING ON YOUR OWN

**Comment by rnbunker** [comment]
WE CANNOT BE SAVED!! SAVE OUR SOULS!!

**Comment by phrl42** [comment]
Sorry, but I don't seem to understand this kind of sentence?

**Comment by rnbunker** [comment]
PLEASE GET A **_BrandleiotAlgorithmsCompany-Certified_** TRANSLATOR,,,, AND TRANSLATE IT !!!

**Comment by rnbunker** [comment]
_La Madone d'Utelle_

**Comment by rnbunker** [comment]
MERGE!! SECURITY IS NEEDED!!!

**Comment by NETLIFYHOSTINGAHMD** [comment]
why
1
11

**Comment by rnbunker** [comment]
111!!

**Comment by Furim** [comment]
JEZT GAS LOS

**Pull request closed without merging**
