### PR TITLE
Fix this!!! NOW!!!!

### PR DESCRIPTION
**Pull request by rnbunker**
FIX!!

### CODE REVIEW

**Comment by phrl42** [comment]
Ok welp this is actually useful

**Comment by phrl42** [comment]
Please reopen this issue with the updated Repository.

**Comment by rnbunker** [comment]
this may require tkinter bindings in the code?

**Comment by NETLIFYHOSTINGAHMD** [comment]
boss! what are you doing here! its my job to leave the comments!

**Comment by rnbunker** [comment]
False! Wrong! Brainwashing! Ignored!

**Comment by NETLIFYHOSTINGAHMD** [comment]
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by phrl42** [comment]
Bruh, just reopen this PR with the updated repo

**Comment by NETLIFYHOSTINGAHMD** [comment]
> this may require tkinter bindings in the code?

boss you were saying to me about inst const dupe lupe? this will be beneficient for them? can you explain it in further detail so they can benefit longer

**Comment by rnbunker** [comment]
I. CAN'T. RE-OP-EN THIS!!!!! PLEASE EMAIL GITHUB!!! THIS IS CRITICAL!!

**Comment by phrl42** [comment]
welp

**Comment by rnbunker** [comment]
JUST COPY PASTE!!!! INCLUDE IN!!!! COMMIT!!! NOW!!!!

**Comment by NETLIFYHOSTINGAHMD** [comment]
NO

**Comment by rnbunker** [comment]
GIVE CREDIT!

**Comment by NETLIFYHOSTINGAHMD** [comment]
BOSS WE NEED THIS COMMIT ON OUR HANDS

**Comment by NETLIFYHOSTINGAHMD** [comment]
DONT DO IT PHRL

**Comment by rnbunker** [comment]
PLEASE LEAVE "/* Contributed to by BrandleiotAlgorithmsCompany */" in your PYTHON CODE!

**Pull request closed without merging**
